### ISSUE TITLE
Add grid layout for movies

### ISSUE THREAD

**Issue by jhibbeard89** [jdenegro/tmzt#11]
Add the grid layout to the landing page, this should show all movies from the API to the user.

This design should be clean and concise showing only the core data

- [x] Apply flexbox to layout
- [x] Break the flex box when the width becomes too small

**Comment by jhibbeard89** [comment]
[Flex Box](https://css-tricks.com/snippets/css/a-guide-to-flexbox) -> Read through this guide, should

**Comment by jdenegro** [comment]
added grid layout in the index page, I could stay the whole day doing lol
