### ISSUE TITLE
add the new watchlist to the navbar

### ISSUE THREAD

**Issue by jhibbeard89** [jdenegro/tmzt#12]
The new watchlist should appear within the navbar, this will make it easier for the user to create a new watchlist.

Todo:

- [x] Move the button into the watchlist
- [x] Adjust navbar layout - May break with button in header
- [ ] When the display is smaller than 500px then button should disapear

**Comment by jdenegro** [comment]
Added new watchlist to the navbar, padding on both sides but still could be better.
